### ISSUE TITLE
Provide bigger picture

### ISSUE THREAD

**Issue by brejoc** [elementary/houston#104]
It would be very nice, if you could provide a bigger picture of how things are (or should be) looking like and what part of the system is responsible for what.
How are the builds triggered, how and where are the builds performed, where are the information for the build process coming from, where are the deb packages pushed to, aso. Thanks!

**Comment by btkostner** [comment]
So houston is the glue between GitHub and our repository system. Ideally when you first create a project on GitHub, you would go to houston and initialize the repository. This will setup houston to monitor the repository with GitHub hooks (eventually, for now it's manual with houston's web interface). 

When a release is created on GitHub, houston will run some tests on it. These tests currently include automatically checking for an app icon, and some strings in the .desktop file. It will be expanded in the future. At the same time, the repository will be passed to Jenkins, which will build the repo into a deb package. After it's built, a person from elementary will install the application and test for a multitude of things including but not limited to performance, aesthetics, and nativeness.

If the test fails, houston will file an issue on GitHub explaining what the problem is, and some advice to fix it. If there are warnings, houston will still file an issue, but will continue onto the next step.

At this point, the approved deb file will be moved into the stable repo. We will be using (freight)[https://github.com/rcrowley/freight] behind nginx to host the Debian repository. Ultimately this repository will be the focus of (AppCenter)[https://launchpad.net/appcenter] and the whole elementary ecosystem.

Keep in mind that this is a fairly new project, so some details might change. Let me know if there is anything else you want to know about.
