### ISSUE TITLE
Solved issues on my project, but Houston doesn't update the status

### ISSUE THREAD

**Issue by luizaugustomm** [elementary/houston#394]
I created new release of my app, but Houston created 3 issues on my github page.
I fixed the issues and closed them, then I came back to AppCenter dashboard. However, the message "com.github.luizaugustomm.tomato has issues that must be resolved" didn't disappear.

PS.: I tried to logout and login again, but that didn't work.

**Comment by Philip-Scott** [comment]
@luizaugustomm have you made a new release of your app after fixing your issues? :) You need to create a new one for Houston to update

**Comment by luizaugustomm** [comment]
@Philip-Scott I just created a new release through GitHub. I refreshed the dashboard page, but nothing changed. 😕

**Comment by btkostner** [comment]
Would you mind trying the dashboard again in 12 hours. We recently added a project cache to avoid expending all our GitHub API calls, and I'm wondering if that had unintended consequences of messing up release detection. Otherwise I'll take a look at the logs when I can to see if a error occurred with the GitHub API

**Comment by btkostner** [comment]
Was it the cache? If so we should look into fixing that, because it shouldn't act that way.

**Comment by luizaugustomm** [comment]
@btkostner, I waited at least 12 hours as you asked me but nothing changed in the dashboard's status. Then, I've created another release and it came back to work.
