### ISSUE TITLE
How the hack this thing work ??

### ISSUE THREAD

**Issue by keshavbhatt** [elementary/houston#455]
I been trying to upload my app from my github repo but i was unable to get my release in dashboard after creating new release. i mean where are docs about how to upload apps , your system don't guide how to it works and what user have to do next . i have lots of apps in ubuntu store already check [them here ](https://uappexplorer.com/apps?type=snappy&q=keshav&sort=relevance)

**Comment by danrabbit** [comment]
There is publishing documentation on the wiki for this repo [here](https://github.com/elementary/houston/wiki/Before-You-Publish)

If you need assistance, please feel free to join [our gitter](https://gitter.im/elementary/houston)

**Comment by keshavbhatt** [comment]
What does this mean ?? What if users don't want to show you the source code of my applications?? 

> It must be hosted in a GitHub repository. AppCenter Dashboard works by importing source code from a GitHub repository and building it in a clean environment. Binaries cannot be uploaded.

**Comment by keshavbhatt** [comment]
Also Qt apps not allowed ?? :octopus:

**Comment by btkostner** [comment]
Currently houston only supports code from GitHub repositories. We do not allow you to upload already created binaries or packages because we do make some changes to the files to allow things like stripe payments.

It is also a long standing condition that apps made for elementary _must_ be made with GTK. This is to create a consistent feel, and for system integration like universal access settings.

**Comment by lewisgoddard** [comment]
Your apps can have private GitHub repositories, but elementary must have source access.
