### ISSUE TITLE
Add support for autotools

### ISSUE THREAD

**Issue by fluks-eos** [elementary/houston#507]
Could it be possible for Houston to also support building with autotools? As I understand, it supports only cmake now? I assume people would like to publish their existing projects in AppCenter and some use autotools.

I tried to publish my app and I get an error: 

> Error Encountered Processing com.github.fluks-eos.gdice. This is most likely a problem with this website.

The error message doesn't really tell the reason, but I suspect the reason is that I use autotools.

**Comment by btkostner** [comment]
If I remember correctly, that error occurred before we even get to testing. It's vague because the error could contain sensitive information. With that said, we should support any build style as long as debuild supports it (which it should). I can't test or look at the logs right now because im AFK, but ill check it this week and report back.

**Comment by fluks-eos** [comment]
Ok, I thought that maybe it was about autotools, because I saw something about cmake in liftoff code and nothing about autotools.

I'm not familiar with building debs and building the package with debuild failed, because it didn't call autogen.sh script.

Now I seem to be in a limbo, publishing the current release fails every time and I can't publish a new release with deb building fixed. I'll try to remove AppCenter's  repo access and add it again.

**Comment by btkostner** [comment]
Found the issue, it's #508. Closing in favor of that.

**Comment by btkostner** [comment]
This has been fixed. You should be able to publish your app now.
