### ISSUE TITLE
Support "normal" and RDN names simultaneously

### ISSUE THREAD

**Issue by jendrikseipp** [elementary/houston#510]
I'm trying to find a solution to the following problem: I'd like to publish the rednotebook app (https://github.com/jendrikseipp/rednotebook) as a Debian package both to the AppCenter and to my Ubuntu PPA. AppCenter requires the package to be named "com.github.jendrikseipp.rednotebook", but in Debian, Ubuntu and in the Ubuntu PPA, the package is named "rednotebook".

My current solution is to maintain a fork for elementary at https://github.com/jendrikseipp/rednotebook-elementary, but this seems tedious. Can you think of a better solution?

**Comment by cassidyjames** [comment]
Non-RDNN names will likely not ever be supported; they require a lot more work to ensure there are no naming collisions. Plus, GTK and Linux app development is moving quickly towards everything being RDNN namespaced, anyway; best practices for .desktops, DBus, GSettings, and Flatpak already are, for example.

We do have an open issue to support arbitrary RDNN schemes (instead of just `com.github`), but that's not quite what you're asking for here

**Comment by jendrikseipp** [comment]
Thanks for the explanation!
