### ISSUE TITLE
Move to using separate packaging branches

### ISSUE THREAD

**Issue by peteruithoven** [elementary/houston#544]
> The insistence of Elementary to include Debian control files directly in the repository (which is problematic, since Debian discourages this and it will make Debian packaging harder, and also the files would be Elementary specific and are not necessarily reusable by Debian or Ubuntu)

From: https://github.com/phw/peek/issues/144#issuecomment-331703969

I'm not sure if this is the right repository for this issue, but it would be a shame if great apps like Peek fall through the cracks.

**Comment by btkostner** [comment]
Yes, this is the correct repository. 

The reason we include the control file and all the other Debian packaging is because we don't want to invent a new standard. We could not include them, but then we would need a way to change the defaults, set your dependencies, etc. 

We have considered a way to include your packaging in another branch, away from your code. But at this point we are just planning how we want to do it.

**Comment by phw** [comment]
Peek developer here. I have two issues with adding the Debian control files to the repository:

1. It is discouraged by Debian's packaging guidelines, as it complicates things for their package maintainers. They prefer adding their own packaging without the need to patch out existing packaging files. I talked to the potential maintainer of a Peek Debian package and he advised me to remove the control files.
2. It would not even be Debian specific, but the debian folder would contain packaging files for Elementary. Maybe the files can be reused for Debian or Ubuntu, but maybe not.

From my experience with maintaining Ubuntu packaging for PPAs on Launchpad I know the second point is an issue. While you often can reuse the packaging for different distribution releases, you quickly end up with 2 or 3 versions just for different Ubuntu releases due to subtle differences in package names and versions.

For that I actually quite like how Launchpad's build recipes allow you to merge in the packaging files from different repositories or branches.

**Comment by danrabbit** [comment]
I'm going to mark this as confirmed and as high priority since we'll need to start doing packaging branches in order to support building apps for both Loki and Juno.

**Comment by peteruithoven** [comment]
Haven't we implemented this already with supporting `deb-packaging-[version]` branches?
https://github.com/elementary/houston/wiki/Before-You-Publish#packaging

**Comment by phw** [comment]
Yes, this sounds exactly like the solution to this issue.

**Comment by btkostner** [comment]
Yes. Closed.
