### ISSUE TITLE
Whitelist io.elementary.* paths

### ISSUE THREAD

**Issue by codygarver** [elementary/houston#589]
Seems Houston expects everything to be `com.github.*` but we need `io.elementary.*` for elementary stuff.

**Comment by codygarver** [comment]
```
Error while running build for https://github.com/elementary/appcenter for 0.0.1
workable: Missing shipped binary at /usr/bin/com.github.elementary.appcenter
  Error: Missing shipped binary at /usr/bin/com.github.elementary.appcenter
      at FileDebBinary.<anonymous> (/home/travis/build/elementary/appcenter/node_modules/@elementaryos/houston/dest/worker/task/file/deb/binary.js:38:23)
      at Generator.next (<anonymous>)
      at fulfilled (/home/travis/build/elementary/appcenter/node_modules/@elementaryos/houston/dest/worker/task/file/deb/binary.js:8:58)
      at <anonymous>
```

**Comment by Philip-Scott** [comment]
But only on elementary repos, so it doesn't allow anyone to pass an app with io.elemetary.* :wink:

**Comment by btkostner** [comment]
I really don't want to make hard coded exceptions in the worker. Luckely the RDNN isn't hard coded for the worker process, so you can just use `--name-domain io.elementary.*` and everything should work as expected. The one thing that _does_ need changing are the icon tests, because right now it expects everything to ship it's own icon.

**Comment by cassidyjames** [comment]
We also talked briefly about a `type: System` instead of the `type: Application` that we use now, which could enforce different requirements. For running tests, I agree just setting the domain makes sense, but eventually we'll want to get our own apps into AppCenter.
