### ISSUE TITLE
Pay by mining cryptocurrency

### ISSUE THREAD

**Issue by jwinnie** [elementary/houston#595]
Many users would rather pay for apps by mining for cryptocurrency (such as Monero).

There could be an option to “pay using your CPU power” that installs a miner on the user’s computer that mines until a certain amount is met (eg $1). The effects (eg fan use, electricity drain) would be explained clearly. The miner would only mine when the CPU is idle, and the user can cancel or pause at any time.

I think this would help elementary’s mission to make Open Source development profitable.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jacob8765** [comment]
Not a bad idea, though the mining part would be a lot of work, and it would be tricky to get the money to the developer since stripe dropped support for cryptocurrencies.

**Comment by jwinnie** [comment]
It could ask the developer for their Monero address when they create their account, and profits from mining would go there.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jwinnie** [comment]
@Jacob8765 I agree that it would be very difficult. It will probably only happen if @elementary makes it a priority.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by harisvsulaiman** [comment]
Nope

**Comment by danrabbit** [comment]
I'm going to close this as a "design conflict" since it seems fairly convoluted and unpopular with the number of :-1:s here. There's also concerns that crypto mining is bad for the environment and it seems mining is no longer profitable unless you have a dedicated mining computer. The end result is also not a currency that developers can use to buy food or pay their bills, so it doesn't really seem like an affective way to compensate them

**Comment by harisvsulaiman** [comment]
Rather than mining on the user system i would rather have users opt into privacy respecting native ads. 🤷🏼
