### ISSUE TITLE
Error on connect Stripe account

### ISSUE THREAD

**Issue by muriloventuroso** [elementary/houston#613]
I'm getting the following error when connecting an app to my account on Stripe:

500
An error occured

I authorize the app in Stripe, but on returning to the Dashboard I get the error message.

App: com.github.muriloventuroso.easyssh

**Comment by btkostner** [comment]
Hello @muriloventuroso 

Sorry about the confusing error. It should be showing nice information but apparently it's not showing correctly. Looking at the server logs it seems that error was thrown because your Stripe account is in preview (more info [here](https://stripe.com/global)). Sadly, Stripe doesn't allow full currency exchanging with accounts still in preview, so AppCenter does not allow linking those accounts yet. As soon as your account gets out of preview mode, it will be able to work with AppCenter.

**Comment by calo001** [comment]
Hi!
Stripe recently arrived officially to Mexico, and I tried to connect with the dashboard and get the same 500 error, Maybe accounts from Mexico still are on preview mode?

**Comment by btkostner** [comment]
Relevant code here: https://github.com/elementary/houston/blob/master/src/houston/passport/stripe.js#L32

**Comment by dar5hak** [comment]
I was trying to connect an Indian account and landed here.

Looking at https://stripe.com/global, Mexico seems to be out of preview (and India is still in). But then Brazil is also in preview. Not sure if I should include that in a PR.
