### ISSUE TITLE
Previous update description shown?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/houston#649]
On eOS Juno, in Appcenter I see the following update for Videos:
![screenshot from 2018-09-20 01-56-26](https://user-images.githubusercontent.com/523210/45788091-cf9bed00-bc78-11e8-92b3-34fc0c66a35c.png)

But this description seems to be the release description of [0.2.6](https://github.com/elementary/videos/blob/master/data/io.elementary.videos.appdata.xml.in#L70-L77) instead of [2.6.1](https://github.com/elementary/videos/blob/master/data/io.elementary.videos.appdata.xml.in#L63-L69)

I've attempted to clear caches by running:
```
sudo appstreamcli refresh-cache --force
sudo apt update
killall io.elementary.appcenter
```

**Comment by btkostner** [comment]
This is most likely an issue with the elementary appstream data package, where it does not include the 2.6.1 appstream changes.

I'll take to Cody and see if we can automate the generation process for that package. In the mean time, because Videos is not built with houston, I'm going to close this issue. The repo for this data is here btw: https://github.com/elementary/appstream-data
