### ISSUE TITLE
`npm install` fails on Travis

### ISSUE THREAD

**Issue by dar5hak** [elementary/houston#755]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
While trying to install `@elementaryos/houston`, node-gyp encounters an error related to `nodegit` package.

### To Reproduce
1. Push to a branch on an AppCenter-enabled repo so that the build is triggered.
2. Go to the Travis build log.
3. See error: `The command "npm i -g @elementaryos/houston" failed and exited with 1 during .`

### Expected behavior

The build installs the package as usual and runs the tests.

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/8205055/67221558-4a6da380-f449-11e9-8c8c-77e5ae28323b.png)

### Logs

See this build for complete error stack and more details:
https://travis-ci.org/elfenware/badger/builds/600805745

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context

NA

**Comment by dar5hak** [comment]
One difference I noticed is how it tries to fetch `nodegit`. In my previous successful builds, it fetched prebuilt binaries of `nodegit` and used those. In this failed build, it couldn't fetch those, so it tried to compile it locally, which didn't work.

**Comment by gamerlv** [comment]
I've checked over the log you linked. The root cause is the new nodejs LTS version, v12,[ that was released on the 21st of this month](https://nodejs.org/en/about/releases/). In your ` .travis.yml ` file you specified you want your test to run on the latest. Previous tests where run with nodejs LTS v10.

Houston-cli has a dependency on nodegit as you see in the error, currently we are using version 0.24. Support for nodejs v12 was only added to nodegit as of version 0.26 (Initial support in [0.25](https://github.com/nodegit/nodegit/commit/485d675f9060110b9f9f6ce581b9b1cff3befdc7) but stabilized in the later version)

For solutions to get your tests green again you could lower the nodejs version back to LTS v10 or wait for us to release an update to houston-cli.

**Comment by dar5hak** [comment]
@gamerlv Ah, that makes sense. Thank you, I'll wait for the update.
