### ISSUE TITLE
I have been waiting for approval of my new elementary os app for months now

### ISSUE THREAD

**Issue by padjis** [elementary/houston#762]
https://github.com/padjis/ghistory

**Comment by cassidyjames** [comment]
Hey @padjis, it appears [version 1.0.0](https://github.com/padjis/ghistory/releases/tag/1.0.0) is in review since 19 days ago, when it was released. I'll bump the review team and see what the status is.

**Comment by padjis** [comment]
Thank you @cassidyjames

**Comment by volfpeter** [comment]
@cassidyjames Same [here](https://github.com/volfpeter/timer). (It looks like gHistory has already passed review and it's in AppCenter.)

**Comment by cassidyjames** [comment]
@volfpeter there was a build system issue recently which had blocked up reviews and we're working back through them. 

Since this is not an issue with Houston itself and is just inviting pile-on, I'm going to close it. If you have a specific issue with Houston or would like to ask a new question, feel free to open a new issue.
