### ISSUE TITLE
Internal error while running

### ISSUE THREAD

**Issue by candiedoperation** [elementary/houston#824]
![Screenshot from 2021-06-08 17 40 01](https://user-images.githubusercontent.com/47198395/121182501-c4ea7180-c880-11eb-951a-3162dd1350e9.png)

Repo: https://github.com/candiedoperation/ordne

**Comment by candiedoperation** [comment]
@cassidyjames, @danrabbit I am unable to send my app for review. It builds and works fine on my desktop...

**Comment by btkostner** [comment]
The https://github.com/candiedoperation/ordne project is failing because it does not include any debian packaging.

Right now elementary is focusing on transitioning to flatpaks, so our documentation is updated for that. You can view it [here](https://docs.elementary.io/develop/writing-apps/our-first-app/packaging). Note that the current dashboard does not work with flatpak though, but there will be an update to it soon.

**Comment by candiedoperation** [comment]
Thank You for the response @btkostner.
BTW, How long will it take for the AppCenter Dashboard Transition to flatpak so that I can submit the app for review?

**Comment by candiedoperation** [comment]
In fact, The app is targeted for Elementary OS 6, Do I need to do `deb packaging` (if so how?) or should I wait for the `flatpak` transition of AppCenter Dashboard?

**Comment by btkostner** [comment]
I would wait for the flatpak transition. It will be done before we release elementary OS 6, so soon. You can follow the progress here https://github.com/elementary/appcenter-dashboard
