### ISSUE TITLE
Internal error while running

### ISSUE THREAD

**Issue by amka** [elementary/houston#831]
Right after Odin has been released I packaged my new apps into [flatpak](https://docs.elementary.io/develop/writing-apps/our-first-app/packaging), add the CI process as it [described](https://docs.elementary.io/develop/writing-apps/our-first-app/continuous-integration) in the docs.

- [Frog](https://github.com/TenderOwl/Frog/issues/3)
- [Turtle](https://github.com/TenderOwl/Turtle/issues)

Found 2 closed issues here, but nothing that helped me.

## What Happened
Houston instantly posts an issue with no description inside and the only text is "Internal error while running". No additional info in the dashboard too.

## Expected Behavior
Some review process or at least error description. Have no idea what to fix.

**Comment by btkostner** [comment]
This houston repository is for the old deb based dashboard. The error you are describing sounds like you used this dashboard for a new flatpak app designed for Odin. 

The new dashboard interface is not yet complete, but if you want to submit your app, you can make a PR against [the reviews repository](https://github.com/elementary/appcenter-reviews) similar to the [other open PRs](https://github.com/elementary/appcenter-reviews/pull/81/files)

**Comment by btkostner** [comment]
Frog: https://github.com/elementary/appcenter-reviews/pull/82

**Comment by btkostner** [comment]
Turtle: https://github.com/elementary/appcenter-reviews/pull/83

**Comment by amka** [comment]
Ah, thank you! I didn't find out that info, maybe we need to add it to the dev. docs? Probably as a temporary notice but visible for anyone

**Comment by athulmessi** [comment]
I loved elementary OS but I can't install Linux os on my Acer aspire ES 15
533 laptop



..............................................................................
My laptop is Acer aspire ES1 ES1-533 it's a Windows default system can't
install non Windows bootloader every single time I tried install Linux os I
try to install elementary , manjaro , elementary all time system freeze at
installing bootloader
So
Elementary  can install without bootloader

can't install grub bootloader can't install auto/manual (terminal)
easyBCD  never work on my laptop . it's clear my EFI folder
I can use  all distro in live boot mode perfectly

*My bios is very limited functions *
**UEFI but very limited capabilities*
**It's cannot be switched to legacy *
**There is no option select an UEFI file as trusted for execution. *
**The only thing which can be done is to enable/disable secure boot.*
..............................................................................

On 19-Aug-2021 4:55 AM, "Andrey M" ***@***.***> wrote:

Ah, thank you! I didn't find out that info, maybe we need to add it to the
dev. docs? Probably as a temporary notice but visible for anyone

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/elementary/houston/issues/831#issuecomment-901494363>,
or unsubscribe
