### ISSUE TITLE
Add a mechanism for approving packages

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#97]
The idea is that packages are automatically built into a testing repo and then we have a human test and approve them to go into the stable repo. We'll need some kind of review queue page that:

- [x] Can only be accessed by members of the houston app reviewers github team
- [x] Lists packages that haven't yet been reviewed for that version/git tag
- [x] Allows the reviewer to approve and upon approval copies the package into stable
- [ ] Allows the reviewer to reject and supply a reason why it was rejected which is filed as an issue

Something to consider is whether rejecting should always delete the package from testing or if we should provide some other mechanism for deleting. I'm thinking of a case where the reason the package is rejected it because it is malicious or otherwise dangerous to install.

**Comment by aroman** [comment]
do you have any design for this? how should these things be accessible via the UI?

**Comment by btkostner** [comment]
If it's malicious it should be removed to avoid accidental installation, but otherwise it should be kept for a small amount of time. Just in case someone else needs / wants to review it. It might not even have to be time based. Something like keep the last two (non malicious) packages submitted for review would work great I think.

**Comment by danrabbit** [comment]
I think this can be closed since the last item here is now #228
